version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  test-front:
    working_directory: ~/OZKOUR/ozkour-front
    executor: node/default
    steps:
      - checkout:
          path: ~/OZKOUR
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests

workflows:
    testing:
      jobs:
        - test-front