version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  fetch_code: 
      steps:
          - checkout
  test:
    working_directory: ~/project/ozkour-front
    docker:
      - image: cimg/node:14.19.3
    steps:
      - node/install-packages
      - run:
          name: Run tests
          command: npm test

workflows:
    example-workflow:
      jobs:
        - fetch_code
        - test