version: 2.1
orbs:
  node: circleci/node@4.7

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - run:
          command: cd ozkour-front
          name: cd ozkour-front
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Run tests

workflows:
  test_ozkour:
    jobs:
      - test