version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  # Below is the definition of your job to test your Node app. You can rename and customize it as you want.
  test:
    working_directory: ~/project/ozkour-front
    # These next lines define a docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # A list of available CircleCI docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/node
    docker:
      - image: cimg/node:14.19.3
    # Then run your tests!
    # CircleCI will report the results back to your VCS provider.
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: Front directory
          command: cd ozkour-front
      # Next, the node orb's install-packages step will install the dependencies from a package.json.
      # The orb install-packages step will also automatically cache them for faster future runs.
      - node/install-packages:
          app-dir: ~/project/ozkour-front
      # If you are using yarn instead npm, remove the line above and uncomment the two lines below.
      # - node/install-packages:
      #     pkg-manager: yarn
      - run:
          name: Run tests
          command: npm test

workflows:
    example-workflow:
      jobs:
        - test