version: 2.1
executors:
  node-img:
    docker:
      - image: 'cimg/node:16.14.0'
jobs:
  test-front:
    executor: node-img
    working_directory: ~/OZKOUR/ozkour-front
    steps:
      - checkout:
          path: ~/OZKOUR
      - run:
          command: npm install
          name: Install dependencies
      - run:
          command: npm run lint
          name: Run linter
      - run:
          command: npm run test:unit
          name: Run tests
      - run:
          command: ls -ail ~/OZKOUR/ozkour-front/test-results
      - store_test_results:
          path: ~/OZKOUR/ozkour-front/test-results
      - store_artifacts:
          path: ~/OZKOUR/ozkour-front/test-results
  test-back:
    executor: node-img
    working_directory: ~/OZKOUR/ozkour-back
    steps:
      - checkout:
          path: ~/OZKOUR
      - run:
          command: npm install
          name: Install dependencies
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: ls -ail ~/OZKOUR/ozkour-back/test-results
      - store_test_results:
          path: ~/OZKOUR/ozkour-back/test-results
      - store_artifacts:
          path: ~/OZKOUR/ozkour-back/test-results
workflows:
  testing:
    jobs:
      - test-front
      - test-back
