version: 2.1
orbs:
  node: circleci/node@4.7

jobs:
  test:
    working_directory: ~/project/ozkour-front
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Run tests

workflows:
  test_front:
    jobs:
      - test